poll/urls.py
from operator import index
from django.urls import include, path
from . import views

urlpatterns = [
    path('', views.get_index, name='index'),
    path('polls/<int:page>', views.get_vote_view, name='polls'),
    path('accounts/register', views.register_request, name="register"),
    path('poll/<int:menu_id>/<int:dish_id>/vote',
         views.make_vote, name='poll-vote'),
    path('poll/create/', views.MenuCreate.as_view(), name='poll-create'),
    path('poll/<int:pk>/update/', views.MenuUpdate.as_view(), name='poll-update'),
    path('poll/<int:pk>/delete/', views.MenuDelete.as_view(), name='poll-delete'),
    path('poll/<int:pk>/', views.poll_detail_view, name='poll-detail'),
    path('dishes/', views.DishListView.as_view(), name='dishes'),
    path('dish/<int:pk>', views.DishDetailView.as_view(), name='dish-detail'),
    path('dish/create/', views.DishCreate.as_view(), name='dish-create'),
    path('dish/<int:pk>/update/', views.DishUpdate.as_view(), name='dish-update'),
    path('dish/<int:pk>/delete/', views.DishDelete.as_view(), name='dish-delete'),
    path('votes/', views.VoteListView.as_view(), name='votes'),
    path('vote/<int:pk>/', views.VoteDetailView.as_view(), name="vote-detail"),
    path('vote/<int:pk>/update/', views.VoteUpdate.as_view(), name='vote-update'),
    path('vote/<int:pk>/delete/', views.VoteDelete.as_view(), name='vote-delete'),
    path('users/', views.UserListView.as_view(), name='users'),
    path('user/<int:pk>/', views.UserDetailView.as_view(), name='user-detail'),
    path('user/<int:pk>/update/', views.UserUpdate.as_view(), name='user-update'),
    path('user/<int:pk>/delete/', views.UserDelete.as_view(), name='user-delete'),
    path('users/', views.UserDelete.as_view(), name='user-list'),
    path('manager/', views.financial_manage, name='financial-manage'),
]

yummie/urls.py
from django.contrib import admin
from django.urls import path
# Use include() to add paths from the poll application
from django.urls import include
# Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('poll.urls')),
    # path('', RedirectView.as_view(url='polls/1', permanent=True)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

poll/models.py
# Used to generate URLs by reversing the URL patterns
from django.urls import reverse
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings


class Dish(models.Model):
    DISH_TYPE = (
        ('f', 'Food'),
        ('d', 'Drink'),
    )
    name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=20, decimal_places=2)
    type = models.CharField(max_length=1, choices=DISH_TYPE,
                            blank=False, default='f', help_text='Dish type')

    class Meta:
        ordering = ['name']

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.name} {self.type} {self.price}'

    def get_absolute_url(self):
        """Returns the URL to access a particular author instance."""
        return reverse('dish-detail', args=[str(self.id)])


class Menu(models.Model):
    dish = models.ManyToManyField(
        Dish, help_text="Select dish for this Menu")
    due = models.DateTimeField()

    class Meta:
        ordering = ['-due']

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.time_seconds()}'

    def get_absolute_url(self):
        """Returns the URL to access a particular author instance."""
        return reverse('poll-detail', args=[str(self.id)])

    def display_dish(self):
        """Create a string for the Dish. This is required to display dish in Admin."""
        return ', '.join(dish.name for dish in self.dish.all())

    def list_dish(self):
        return self.dish.all()

    display_dish.short_description = 'dish list'

    def time_seconds(self):
        return self.due.strftime("%d/%m/%Y, %H:%M")

    time_seconds.short_description = 'menu due' 


class Vote(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True)
    menu = models.ForeignKey(
        Menu, on_delete=models.SET_NULL, null=True, blank=True)
    user_name = models.CharField(max_length=300)
    DISH_LIST = ((i['name'], i['name'])
                 for i in Dish.objects.all().values('name'))
    dish_name = models.CharField(
        max_length=300, choices=DISH_LIST, blank=True, null=True, help_text='Dish')
    cost = models.DecimalField(max_digits=20, decimal_places=2)
    vote_as = models.CharField(max_length=100, null=True, blank=True)
    created_at = models.DateTimeField()

    class Meta:
        ordering = ['-created_at', 'dish_name']

    def get_absolute_url(self):
        """Returns the URL to access a particular author instance."""
        return reverse('vote-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.user_name} {self.dish_name} {self.created_at}'

    # def time_seconds(self):
    #     return self.created_at.strftime("%d/%m/%Y, %H:%M")

    # time_seconds.short_description = 'created time' 


USER_GENDER_CHOICES = [
    (0, 'Not declared'),
    (1, 'Male'),
    (2, 'Female'),
]

class User(AbstractUser):
    gender = models.PositiveSmallIntegerField("Gender", choices=USER_GENDER_CHOICES, default=0)
    # add additional fields in here

    def __str__(self):
        return self.username

    def get_user_name(self):
        if self.first_name or self.last_name:
            return self.first_name + " " + self.last_name
        return self.username

    def get_absolute_url(self):
        """Returns the URL to access a particular author instance."""
        return reverse('user-detail', args=[str(self.id)])


# User.add_to_class("get_user_name", get_user_name)
# User.add_to_class("get_absolute_url", lambda self: reverse(
#     'user-detail', args=[str(self.id)]))

poll/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.forms import ModelForm
from .models import Menu, User


# Create your forms here.


class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "first_name",
                  "last_name", "gender", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = User
        fields = ("username", "email")


class NewVoteForm(forms.Form):
    btn = forms.CharField()


class NewPollForm(forms.Form):
    vote = forms.CharField(
        widget=forms.CheckboxInput(
            attrs={
                'class': 'form-check-input',
                'onclick': 'this.form.submit();',
            }
        ),
        label=False,
    )


class DateInput(forms.DateInput):
    input_type = 'date'


class MenuForm(ModelForm):
    class Meta:
        model = Menu
        fields = ['dish', 'due']
        widgets = {
            'due': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'id': 'picker',
                }
            ),
        }

poll/views.py
from urllib import request
from django.conf import settings
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render, redirect
from .models import Dish, Menu, Vote, User
from .forms import MenuForm, NewUserForm, NewVoteForm
from django.contrib.auth import login
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse, reverse_lazy
import datetime
from django.views import generic
from django.core.paginator import Paginator, EmptyPage
import pytz
from django.utils import timezone

HOME_URL = '/'
DISH_LIST_URL = '/dishes/'


def total_seconds(td):
    if hasattr(td, 'total_seconds'):
        return td.total_seconds()
    else:
        return (td.microseconds + (td.seconds + td.days * 24 * 3600) * 10**6) / 10**6


def convert_to_localtime(utc_time):
    utc = utc_time.replace(tzinfo=pytz.UTC)
    return utc.astimezone(timezone.get_current_timezone())


def add_votes_info_to_poll(menu):
    results = {}
    votes = Vote.objects.filter(menu_id=menu.id)
    for item in menu.list_dish():
        arr = []
        for vote in votes:
            if item.name == vote.dish_name:
                arr.append(vote)
        results[item.name] = arr
    return {'menu': menu, 'votes': votes, 'results': results}


def get_index(request):
    today_min = datetime.datetime.combine(
        datetime.date.today(), datetime.time.min)
    today_max = datetime.datetime.combine(
        datetime.date.today(), datetime.time.max)
    this_month = datetime.datetime.now().month

    results = Menu.objects.filter(
        due__range=(today_min, today_max)).order_by('due')
    menu_list = map(add_votes_info_to_poll, results)
    user_votes = Vote.objects.filter(user_id=request.user.id)
    user_total_cost = 0
    for vote in user_votes:
        user_total_cost += vote.cost

    return render(request, 'index.html', context={
        "menu_list": menu_list,
        "user_votes": user_votes,
        "this_month": this_month,
        "user_total_cost": user_total_cost,
    })


def get_vote_view(request, page=1):
    menu_list = map(add_votes_info_to_poll, Menu.objects.all())
    paginator = Paginator(list(menu_list), 3)
    try:
        menu_list = paginator.page(page)
    except EmptyPage:
        # if we exceed the page limit we return the last page
        menu_list = paginator.page(paginator.num_pages)
    return render(request, 'poll/polls.html', context={
        "menu_list": menu_list,
    })


def register_request(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful.")
            return HttpResponseRedirect(HOME_URL)
        messages.error(
            request, "Unsuccessful registration. Invalid information.")
    form = NewUserForm()
    return render(request=request, template_name="registration/register.html", context={"register_form": form})


class MenuCreate(SuccessMessageMixin, LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Menu
    form_class = MenuForm
    success_message = "The %(due)s menu was created successfully"
    # success_url = '/success/'

    def test_func(self):
        return self.request.user.is_superuser

    def handle_no_permission(self):
        return HttpResponseRedirect(HOME_URL)


class MenuUpdate(SuccessMessageMixin, LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    success_message = 'Successfully updated the %(due)s menu!'
    model = Menu
    form_class = MenuForm
    # Not recommended (potential security issue if more fields added)
    # fields = '__all__'

    def test_func(self):
        return self.request.user.is_superuser

    def handle_no_permission(self):
        return HttpResponseRedirect(HOME_URL)


class MenuDelete(SuccessMessageMixin, LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Menu
    success_message = 'Successfully deleted the %(due)s menu!'
    success_url = reverse_lazy('polls', args=[1])

    def test_func(self):
        return self.request.user.is_superuser

    def handle_no_permission(self):
        return HttpResponseRedirect(HOME_URL)


class DishCreate(SuccessMessageMixin, LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Dish
    success_message = 'Successfully created the %(name)s dish!'
    fields = ['name', 'price', 'type']
    template_name = 'dish/dish_form.html'

    def test_func(self):
        return self.request.user.is_superuser

    def handle_no_permission(self):
        return HttpResponseRedirect(HOME_URL)


class DishUpdate(SuccessMessageMixin, LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Dish
    # Not recommended (potential security issue if more fields added)
    success_message = 'Successfully updated the %(name)s dish!'
    fields = '__all__'
    template_name = 'dish/dish_form.html'

    def dispatch(self, request, *args, **kwargs):
        # here you can make your custom validation for any particular user
        if not request.user.is_superuser:
            messages.error(request, 'Permission Denied!')
        # return HttpResponseRedirect(HOME_URL)
        return super().dispatch(request, *args, **kwargs)

    def test_func(self):
        return self.request.user.is_superuser

    def handle_no_permission(self):
        return HttpResponseRedirect(HOME_URL)


class DishDelete(SuccessMessageMixin, LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Dish
    success_message = 'Successfully deleted dish!'
    success_url = reverse_lazy('dishes')
    template_name = 'dish/dish_confirm_delete.html'

    def dispatch(self, request, *args, **kwargs):
        # here you can make your custom validation for any particular user
        if not request.user.is_superuser:
            messages.error(request, 'Permission Denied!')
        return super().dispatch(request, *args, **kwargs)

    def test_func(self):
        return self.request.user.is_superuser

    def handle_no_permission(self):
        return HttpResponseRedirect(HOME_URL)


class DishListView(generic.ListView):
    template_name = 'dish/dish_list.html'
    model = Dish


class DishDetailView(generic.DetailView):
    template_name = 'dish/dish_detail.html'
    model = Dish


def poll_detail_view(request, pk):
    menu = Menu.objects.get(pk=pk)
    votes = Vote.objects.filter(menu_id=pk)
    return render(request, 'poll/poll_detail.html', context={
        "menu": menu,
        "votes": votes,
    })


class VoteDetailView(generic.DetailView):
    template_name = 'vote/vote_detail.html'
    model = Vote


class VoteListView(generic.ListView):
    template_name = 'vote/vote_list.html'
    model = Vote


@login_required
def make_vote(request, menu_id, dish_id):
    try:
        try:
            menu = Menu.objects.get(pk=menu_id)
        except Menu.DoesNotExist:
            raise Http404('Menu does not exist')
        try:
            dish = Dish.objects.get(pk=dish_id, menu=menu_id)
        except Menu.DoesNotExist:
            raise Http404('Dish does not exist')
        user = request.user
        flag = True
        if Vote.objects.filter(menu_id=menu_id, dish_name=dish.name, user_id=user.id).exists():
            flag = False
        if request.method == 'POST':
            form = NewVoteForm(request.POST)
            if form.is_valid():
                val = form.cleaned_data.get("btn")
                # if request.POST.get('btn') == 'vote' and total_seconds(convert_to_localtime(menu.due).replace(tzinfo=None) - datetime.datetime.now().replace(tzinfo=None)) > 0:
                if val == 'vote' and total_seconds(convert_to_localtime(menu.due).replace(tzinfo=None) - datetime.datetime.now().replace(tzinfo=None)) > 0:
                    Vote.objects.create(
                        user_id=user.id, menu_id=menu.id, user_name=user.get_user_name(), dish_name=dish.name, cost=dish.price, created_at=datetime.datetime.now())
                    messages.success(
                        request, 'Vote has been successful created!')
                else:
                    vote = Vote.objects.filter(
                        menu_id=menu_id, dish_name=dish.name, user_id=user.id)
                    vote.delete()
                    messages.error(request, 'Vote has been canceled!')
                return HttpResponseRedirect(HOME_URL)
            else:
                messages.warning(request, 'Please correct the error below.')
        else:
            form = NewVoteForm()

        return render(request, 'vote/vote_create.html', context={
            'form': form,
            'menu': menu,
            'dish': dish,
            'flag': flag,
        })

    except Exception as e:
        print(e)
        return HttpResponseRedirect(HOME_URL)


class VoteUpdate(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = Vote
    success_message = 'Successfully updated the %(dish_name)s vote of %(user_name)s!'
    # Not recommended (potential security issue if more fields added)
    fields = '__all__'
    template_name = 'vote/vote_form.html'

    def get_object(self, *args, **kwargs):
        obj = super(VoteUpdate, self).get_object(*args, **kwargs)
        if not self.request.user.is_superuser and not obj.user == self.request.user:
            raise Http404  # maybe you'll need to write a middleware to catch 403's same way
        return obj

    def handle_no_permission(self):
        return HttpResponseRedirect(HOME_URL)


class VoteDelete(SuccessMessageMixin, LoginRequiredMixin, DeleteView):
    model = Vote
    success_message = 'Successfully deleted the %(dish_name)s vote of %(user_name)s!'

poll/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block title %}
    <title>Yummie</title>
    {% endblock %}
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />
    <!-- Font Awesome -->
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
      rel="stylesheet"
    />
    <!-- Google Fonts -->
    <link
      href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
      rel="stylesheet"
    />
    <!-- MDB -->
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.3.0/mdb.min.css"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.7.14/css/bootstrap-datetimepicker.min.css"
    />
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
  </head>
  <body>
    {% include 'navbar.html' %}
    <div class="container-fluid py-3 bg-light">
      {% if messages %}
      <ul class="messages">
        {% for message in messages %}
        <div
          {% if message.tags == 'error' %}
          class="{{ message.tags }} alert alert-danger alert-dismissible fade show w-35 position-absolute top-0 end-0"
          {% else %}
          class="{{ message.tags }} alert alert-success alert-dismissible fade show w-35 position-absolute top-0 end-0"
          {% endif %}
          
          style="z-index: 99"
          role="alert"
        >
          {{ message }}
          <button
            type="button"
            class="close"
            data-dismiss="alert"
            aria-label="Close"
          >
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endfor %}
      </ul>
      {% endif %} {% block content %}{% endblock %}
    </div>
    {% include 'footer.html' %}
  </body>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script
    src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"
  ></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.15.1/moment.min.js"></script>
  <!-- MDB -->
  <script
    type="text/javascript"
    src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.3.0/mdb.min.js"
  ></script>
  <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.9/jquery.datetimepicker.css"
    integrity="sha512-bYPO5jmStZ9WI2602V2zaivdAnbAhtfzmxnEGh9RwtlI00I9s8ulGe4oBa5XxiC6tCITJH/QG70jswBhbLkxPw=="
    crossorigin="anonymous"
    referrerpolicy="no-referrer"
  />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.7.14/js/bootstrap-datetimepicker.min.js"></script>
  <script
    src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.9/jquery.datetimepicker.full.min.js"
    integrity="sha512-hDFt+089A+EmzZS6n/urree+gmentY36d9flHQ5ChfiRjEJJKFSsl1HqyEOS5qz7jjbMZ0JU4u/x1qe211534g=="
    crossorigin="anonymous"
    referrerpolicy="no-referrer"
  ></script>
  <script>
    $(".alert")
      .delay(2000)
      .slideUp(200, function () {
        $(this).alert("close");
      });
    $(function () {
      $("#datetimepicker1").datetimepicker();
    });
    $("#picker").datetimepicker({
      timepicker: true,
      datepicker: true,
      format: "Y-m-d H:i",
      hours12: false,
      step: 5,
    });
  </script>
</html>

poll/templates/financial_manage.html
{% extends "base_generic.html" %} {% block content %}
<table class="table">
  <thead class="thread-dark">
    <tr>
      <th scope="col">#</th>
      {% for user in user_list %}
      <th scope="col">{{user.get_user_name}}</th>
      {% endfor %}
    </tr>
  </thead>
  <tbody>
    {% for menu_instance in menu_list %}
    <tr>
      <th scope="row">{{menu_instance.menu.due|date:'d/m/Y, H:i'}}</th>
      {% for item in menu_instance.results %}
      <td>{{item}}</td>
      {% endfor %}
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

poll/templates/footer.html
<!-- Footer -->
<footer class="text-center text-lg-start bg-light text-muted">
  <!-- Section: Social media -->
  <section
    class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom"
  >
    <!-- Left -->
    <div class="me-5 d-none d-lg-block">
      <span>Get connected with us on social networks:</span>
    </div>
    <!-- Left -->

    <!-- Right -->
    <div>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-facebook-f"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-twitter"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-google"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-instagram"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-linkedin"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-github"></i>
      </a>
    </div>
    <!-- Right -->
  </section>
  <!-- Section: Social media -->

  <!-- Section: Links  -->
  <section class="">
    <div class="container text-center text-md-start mt-5">
      <!-- Grid row -->
      <div class="row mt-3">
        <!-- Grid column -->
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
          <!-- Content -->
          <h6 class="text-uppercase fw-bold mb-4">
            <i class="fas fa-gem me-3"></i>Company name
          </h6>
          <p>
            Here you can use rows and columns to organize your footer content.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit.
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">Products</h6>
          <p>
            <a href="#!" class="text-reset">Angular</a>
          </p>
          <p>
            <a href="#!" class="text-reset">React</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Vue</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Laravel</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">Useful links</h6>
          <p>
            <a href="#!" class="text-reset">Pricing</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Settings</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Orders</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Help</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
          <p><i class="fas fa-home me-3"></i> New York, NY 10012, US</p>
          <p>
            <i class="fas fa-envelope me-3"></i>
            info@example.com
          </p>
          <p><i class="fas fa-phone me-3"></i> + 01 234 567 88</p>
          <p><i class="fas fa-print me-3"></i> + 01 234 567 89</p>
        </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row -->
    </div>
  </section>
  <!-- Section: Links  -->

  <!-- Copyright -->
  <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05)">
    © 2021 Copyright:
    <a class="text-reset fw-bold" href="https://mdbootstrap.com/"
      >MDBootstrap.com</a
    >
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->